GET https://elasticsearch.openshift-logging.svc.cluster.local:9200/
Authorization: Bearer XXXX

POST http://docker.for.mac.localhost:8080/trasaction/trans HTTP/1.1
Content-Type: application/json

{
    "transactionNo": 435,
    "amount": 1430
}

PUT http://my-connect-cluster-connect-api-debezium-cdc.apps.cluster-mel-dbz-2189.mel-dbz-2189.example.opentlc.com/connectors/debezium-connector-mysql/config
Content-Type: application/json
{
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.user": "root",
    "database.server.id": "184054",
    "tasks.max": "1",
    "database.history.kafka.bootstrap.servers": "my-cluster-kafka-bootstrap:9092",
    "database.history.kafka.topic": "changes-topic",
    "transforms": "route",
    "database.server.name": "sampledb",
    "database.port": "3306",
    "decimal.handling.mode": "double",
    "database.hostname": "mysql",
    "database.password": "password",
    "name": "debezium-connector-mysql",
    "database.whitelist": "sampledb",
    "snapshot.mode": "when_needed"
}